services:
  letmesee:
    # build: .
    image: registry.internal/asano/letmesee:latest
    restart: unless-stopped
    container_name: letmesee
    #ports:
    #  - "3000:8080"
    volumes:
      - ./config.yaml:/letmesee/config.yaml:ro
      - /mnt/200g_ssd500g/dictionary/epwing:/mnt/zotero/dictionary/epwing:ro
    networks:
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.go-letmesee.rule=Host(`letmesee.app.internal`)
networks:
  traefik_net:
    external: true
