package main

import (
	"html/template"
	"log"
	"os"
	"path/filepath"
)

// Templates mirror the skel/ directory from the original Ruby application.
// Each template uses the same CSS class names as the default theme so that
// existing tDiary-compatible stylesheets keep working unchanged.
//
// Templates are loaded from the "static/templates/" directory on disk at
// startup so they can be edited without recompiling.  The built-in strings
// below are fallbacks used when the corresponding file is missing, keeping
// the binary self-contained for development.

// staticTemplatesDir is the directory scanned for on-disk template overrides.
const staticTemplatesDir = "static/templates"

// tmplHeader is the page header, equivalent to skel/header.rhtml.
const tmplHeader = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html lang="ja">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="content-style-type" content="text/css">
    <link rel="stylesheet" href="{{.ThemeCSS}}" type="text/css" media="all">
    <title>let me see...</title>
  </head>
  <body>
    {{.Header}}
    <form method="get" action="{{.IndexURL}}">
      <div>
        <input name="query" size="20" value="{{.Query}}">
        <input type="submit" value="検索">
        検索方法：
        <select name="mode">
          <option value="exactsearch"{{if eq .Mode "exactsearch"}} selected{{end}}>完全一致</option>
          <option value="search"{{if eq .Mode "search"}} selected{{end}}>前方一致</option>
          <option value="endsearch"{{if eq .Mode "endsearch"}} selected{{end}}>後方一致</option>
          <option value="keywordsearch"{{if eq .Mode "keywordsearch"}} selected{{end}}>条件検索</option>
          <option value="menu">メニュー</option>
          <option value="copyright">著作権表示</option>
        </select>
        　辞書毎の最大ヒット数：
        <select name="maxhit">
          <option{{if eq .MaxHit 10}} selected{{end}} value="10">10</option>
          <option{{if eq .MaxHit 20}} selected{{end}} value="20">20</option>
          <option{{if eq .MaxHit 50}} selected{{end}} value="50">50</option>
        </select>
      </div>
      <p>辞書一覧</p>
      <table cellpadding="0" width="100%">
        {{range .DictRows}}
        <tr>
          {{range .}}
          <td>{{if .Valid}}
            <input type="checkbox" name="dict" value="{{.Index}}"{{if .Checked}} checked{{end}}>{{.Title}}
          {{end}}</td>
          {{end}}
        </tr>
        {{end}}
      </table>
`

// tmplFooter is the page footer, equivalent to skel/footer.rhtml.
const tmplFooter = `    </form>
    <hr class="sep">
    {{.Footer}}
    <div class="footer">
      Generated by <a href="http://openlab.jp/edict/letmesee/">let me see...</a>
      (Go port).
    </div>
  </body>
</html>
`

// tmplHelp is shown when no query is present, equivalent to skel/help.rhtml.
const tmplHelp = `    <hr class="sep">
    <div class="day">
      <h2><span class="date">let me see... の使い方</span></h2>
      <div class="body">
        <div class="section">
          <p>検索する辞書を選んで、上部のテキストボックスに検索したい文字列を入力してから
          [検索] をおしてください。</p>
          <p>メニュー検索を行ったり著作権を表示したりする場合は、検索方法のプルダウンメニュー
          から「メニュー」または「著作権表示」を選んで、[検索] を押してください。</p>
        </div>
      </div>
      <div class="referer"></div>
    </div>
`

// tmplSearch renders search results, equivalent to skel/search.rhtml.
const tmplSearch = `{{range .Results}}
    <hr class="sep">
    <div class="day">
      <h2><span class="date">{{.DictTitle}} Hit:{{len .Hits}}</span></h2>
      <div class="body">
        {{range .Hits}}
        <div class="section">
          <h3>{{$.SectionAnchor}}{{.Heading}}</h3>
          <p class="content">{{.Content}}</p>
        </div>
        {{end}}
      </div>
      <div class="referer"></div>
    </div>
{{end}}
{{if .SpellResults}}
    <hr class="sep">
    <div class="day">
      <h2><span class="date">スペル・チェッカー</span></h2>
      <div class="body">
        {{range .SpellResults}}
        <div class="section">
          <h3>{{.Dict}}</h3>
          <p class="content">
            <input type="hidden" name="mode" value="exactsearch">
            {{range .Words}}
            <input type="submit" name="query" value="{{.}}">
            {{end}}
          </p>
        </div>
        {{end}}
      </div>
      <div class="referer"></div>
    </div>
{{end}}
`

// tmplMenu renders a menu or copyright entry, equivalent to skel/menu.rhtml.
const tmplMenu = `{{range .Entries}}
    <hr class="sep">
    <div class="day">
      <h2><span class="date">{{.DictTitle}}</span></h2>
      <div class="body">
        <div class="section">
          <p class="content">{{.Content}}</p>
        </div>
      </div>
      <div class="referer"></div>
    </div>
{{end}}
`

// tmplReference renders a reference (cross-link) target, equivalent to
// skel/reference.rhtml.
const tmplReference = `{{with .Item}}
    <hr class="sep">
    <div class="day">
      <h2><span class="date">{{$.DictTitle}}</span></h2>
      <div class="body">
        <div class="section">
          <p class="content">{{.}}</p>
        </div>
      </div>
      <div class="referer"></div>
    </div>
{{end}}
`

// loadTemplate reads a template from static/templates/<name> on disk if the
// file exists, falling back to the supplied built-in string.  This lets
// operators customise templates without recompiling the binary.
func loadTemplate(name, builtin string) *template.Template {
	path := filepath.Join(staticTemplatesDir, name)
	if data, err := os.ReadFile(path); err == nil {
		t, err := template.New(name).Parse(string(data))
		if err != nil {
			log.Printf("template %s: parse error: %v — using built-in", path, err)
		} else {
			return t
		}
	}
	return template.Must(template.New(name).Parse(builtin))
}

// Parsed template instances, initialised once at startup.
var (
	tHeader    = loadTemplate("header.html", tmplHeader)
	tFooter    = loadTemplate("footer.html", tmplFooter)
	tHelp      = loadTemplate("help.html", tmplHelp)
	tSearch    = loadTemplate("search.html", tmplSearch)
	tMenu      = loadTemplate("menu.html", tmplMenu)
	tReference = loadTemplate("reference.html", tmplReference)
)
