services:
  letmesee-orig:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letmesee-orig
    restart: always
    volumes:
      - /mnt/zotero/dictionary/epwing:/usr/local/dict:ro
      - ./letmesee.conf:/usr/local/apache2/htdocs/letmesee.conf:ro
    # Uncomment to access directly without Traefik:
    # ports:
    #   - "8081:80"
    networks:
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.letmesee-orig.rule=Host(`letmesee-orig.app.internal`)
networks:
  traefik_net:
    external: true
